name: Terraform Workflow
on:
  push:
    branches:
      - '**'

jobs:
  tf-plan:
    name: Terraform Checks and Plan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: "."
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
